langfuse:
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      memory: "2Gi"
  salt:
    value: salt
  nextauth:
    secret:
      value: secret

postgresql:
  deploy: true
  auth:
    username: admin
    password: password123

clickhouse:
  deploy: true

redis:
  deploy: true
  auth:
    password: password123
