replicaCount: 1

masterkey: ""

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    memory: "2Gi"

service:
  type: ClusterIP
  port: 4000

envVars: {}

proxy_config:
  model_list:
    - model_name: vllm/qwen3-8b-neuron
      litellm_params:
        model: openai/qwen3-8b-neuron
        api_key: fake-key
        api_base: http://qwen3-8b-neuron.vllm:8000/v1
    - model_name: bedrock/claude-4.5-sonnet
      litellm_params:
        model: bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0
        aws_region_name: us-east-2
  general_settings:
    master_key: os.environ/PROXY_MASTER_KEY
  litellm_settings:
    success_callback:
      - langfuse
    drop_params: true
    cache: true
    cache_params:
      type: redis
      host: litellm-redis-master
      port: 6379

postgresql:
  architecture: standalone
  auth:
    username: litellm
    database: litellm
    password: password123
    postgres-password: password123

redis:
  enabled: true
  architecture: standalone
