apiVersion: v1
kind: Pod
metadata:
  name: s3-irsa-test
  namespace: default
spec:
  serviceAccountName: s3-irsa-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command: ["sleep", "3600"]
