apiVersion: v1
kind: Pod
metadata:
  name: s3-pod-identity-test
  namespace: default
spec:
  serviceAccountName: s3-pod-identity-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command: ["sleep", "3600"]
