apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: dev-team
spec:
  serviceAccountName: dev-k8s
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
