apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-scaleout
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cas-scaleout
  template:
    metadata:
      labels:
        app: cas-scaleout
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: NotIn
                    values: ["system"]
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 800m
              memory: 800Mi
